### ISSUE TITLE
using crunch instead of the current system to embed skel files

### ISSUE THREAD

**Issue by zapashcanon** [OCamlPro/drom#10]
We could use [crunch](https://opam.ocaml.org/packages/crunch/) to embed all the skeletons files, which should be much easier to deal with than the current system. Here's a [minimal example](https://github.com/Armael/stone/blob/master/src/dune#L4) of using crunch to embed some files.

I'm willing to implement it, but let's discuss it first.

**Comment by lefessan** [comment]
I have had a look at `crunch`, and I am not sure it's worth the change. `skel_packer` is small and does not introduce new dependencies, contrary to `crunch`. I would argue to keep it and only switch to `crunch` in the future if the maintenance burden of `skel_packer` becomes greater than zero.

**Comment by lefessan** [comment]
PR #58 installs skeletons in `share/drom` instead of embedding them in the code, so there is no need for `crunch` or `skel_packer` anymore.
