### ISSUE TITLE
scripts copied with wrong chmod

### ISSUE THREAD

**Issue by ocpmax** [OCamlPro/drom#109]
scripts from virtual project (before.sh, after.sh, copy-bin.sh) are not executable in a new project

**Comment by ocpmax** [comment]
I cannot find where to fix this

**Comment by lefessan** [comment]
It was the case in a previous version, but it is supposed to be fixed now in `master`. Can you reproduce the problem ?
(the `write_file` function now performs a `chmod` when necessary)

**Comment by ocpmax** [comment]
yes for all my projects created from master branch, the script files are not executable ( I have to do a `chmod +x scripts/*` for the `make` to work)

**Comment by zapashcanon** [comment]
I believe it's been fixed in #114. Can you still reproduce @ocpmax ?
