### ISSUE TITLE
publishing virtual packages

### ISSUE THREAD

**Issue by Ninjapouet** [OCamlPro/drom#145]
I don't understand how to publish virtual packages with drom. Virtual skeleton seems to be an information only used by drom and not propagated to opam as no .opam file is generated nor published when drom publish is used. Can we create opam virtual packages through drom or should we manually write the .opam file ? The latter solution seems quite ugly since all needed informations are in the dune-project generated by drom but we can't even use dune to generate the missing .opam files for generate_opam_files is set to false.

**Comment by lefessan** [comment]
Yes, at this time, there is no simple way to generate the corresponding opam file. How would you do it with `dune-project` ?

**Comment by Ninjapouet** [comment]
It works, thanks!
