### ISSUE TITLE
dune 3.x support

### ISSUE THREAD

**Issue by struktured** [OCamlPro/drom#188]
Are there plans to migrate drom to use dune 3? I noticed the underlying ocp stack drom depends on also has dune 2.x upper bounds so I imagine this isn't that easy to accomplish.

**Comment by hra687261** [comment]
The current version available on opam seems to support dune 3

**Comment by struktured** [comment]
> The current version available on opam seems to support dune 3

Yes! It is working for me now without downgrading dune. Excited to try this out on my projects. Thanks!
