### ISSUE TITLE
Available on public opam repository?

### ISSUE THREAD

**Issue by roddyyaga** [OCamlPro/drom#54]
Looks like a very useful project! The docs say "if drom is available in your opam repository, you can just call: opam install drom" but it doesn't seem to be available on standard opam. Is there a repo that has it?

**Comment by zapashcanon** [comment]
Not yet, we're planning a release soon but we'd like to fix a few things before.

**Comment by zapashcanon** [comment]
It's been [published on opam](https://github.com/ocaml/opam-repository/pull/17687/files). We will announce it soon, so I'm closing.
