### ISSUE TITLE
potential feature: tutorial directory configured to use lipsum or mdx

### ISSUE THREAD

**Issue by kanishka-work** [OCamlPro/drom#57]
(I'm still studying how it works, so I may have the details wrong)

Consider adding the following as part of new project default:
- a directory called "tutorials"
- inside the directory, populate some starter files for a tutorial similar to https://github.com/lindig/lipsum/tree/master/examples

Feel free to substitute any other project that is similar to lipsum.

**Comment by zapashcanon** [comment]
I didn't know about `lipsum`. There's also [mdx](https://github.com/realworldocaml/mdx/) which has probably received more attention.

**Comment by kanishka-work** [comment]
mdx is definitely awesome. I'm not sure if everyone will want to take it on a build or runtime dependency of their library.

**Comment by zapashcanon** [comment]
> I'm not sure if everyone will want to take it on as a build or runtime dependency of their library.

If we just use it for the `examples` directory, there's no reason to make the library depend on it, right ?

**Comment by kanishka-work** [comment]
Still learning about it, so not sure??

**Comment by kanishka-work** [comment]
> there's no reason to make the library depend on it, right ?

This is mostly true. You could have two separate dune projects, and only use mdx in the dune project for the tutorial.

Also, there is a feature mdx where it will be in charge of splicing in contents of a ocaml file into a markdown file at a specific location. Using that feature, one can keep the ocaml code separate and compile it using a regular ocaml build, and use dune to update the markdown file.

**Comment by kanishka-work** [comment]
I am not actively thinking about tutorials right now, so will close this. If I start writing some in the future, I will reopen this
