### ISSUE TITLE
drom project overwrites .ocp-indent if it's the default one

### ISSUE THREAD

**Issue by zapashcanon** [OCamlPro/drom#7]
Hi,

Running `drom project` in an already existing drom project will overwrite the `.ocp-indent` existing file if it is the default one and the user has one in `"$XDG_CONFIG_HOME/ocp/`.

That's annoying in the following case:

- I want to contribute to e.g. `OCamlPro/drom` (which use the default `.ocp-indent` file)
- I change something in `drom.toml` and thus, I run `drom project` to update everything
- The `.ocp-indent` file is replaced by the one I have in `"$XDG_CONFIG_HOME/ocp/`, which is something I didn't wanted

I guess we should either:

- copy the file in `"$XDG_CONFIG_HOME/ocp/` only if there isn't one in the current drom project (and eventually, add an option to `drom project` which allows the user to copy the file anyway, but that shouldn't be the default !)
- ask the user if he wants to overwrite the file (with default option being not to overwrite it)

I'm willing to implement any of it, but I'd like to discuss it first.

**Comment by lefessan** [comment]
Indeed, it's the same for the `.ocamlformat` file too. 
If you look at the skeleton file for `.ocp-indent` in `src/drom_lib/skeletons/projects/virtual/dot_ocp-indent`, you will see the `!{global-ocpindent}` substitution that triggers the following code in `subst.ml`:
```
 | "global-ocpindent" -> (
      match Ocpindent.find_global () with
      | None -> ""
      | Some content -> raise (ReplaceContent content) )
```
Indeed, I would either suggest to completely remove this code (we only take the file from the skeleton), or use the user's file only if no file is present (in which case we should set an option to prevent us from later upgrading the file using the skeleton). It's probably not worth the complexity, so I would be inclined to choose the first option...

Note that we could add `!(ocp-indent-trailer)` to the skeleton file, and set a field (in `[project.fields]`) `ocp-indent-trailer` in the `drom.toml` file that could be initialized using the user config. This way, the skeleton file could still be upgraded and the problem would not appear anymore.

**Comment by zapashcanon** [comment]
I suggest to add a `find_local` function to `ocamlformat.ml` and `ocpindent.ml` then, in `subst.ml` to replace:

```ml
| Some content -> raise (ReplaceContent content) )
```

by:

```ml
| Some content -> if Option.is_none (find_local ...) raise (ReplaceContent content) )
```

We could add a separate command to replace it later anyway. What do you think ?
