### ISSUE TITLE
Install more packages when `drom build` is executed

### ISSUE THREAD

**Issue by francoisthire** [OCamlPro/drom#73]
When I execute `drom build -y` for the first time, it sets up a new local opam repository. In this repository, `merlin`, `drom`, `tuareg`, `ocamlformat` are not installed, maybe they should be installed, no?

**Comment by lefessan** [comment]
Strictly speaking, these packages are not dependencies of the project, so there is no need to install them to build the project. `ocamlformat` is normally added as a dev dependency (for tests) of the project, so it will be installed with `drom dev-deps`. 
It's also difficult to decide which packages should be installed that way, as some users may have different preferences. 

Maybe such a list could be specified in the `~/.config/drom/config` file, and installed when `drom dev-deps` is called.

**Comment by zapashcanon** [comment]
I made a draft PR (#75), comments are welcome. :)

**Comment by lefessan** [comment]
PR #71 also provides a solution for this (`dev-tools` field in `~/.config/drom/config`)

**Comment by lefessan** [comment]
PR #71 was merged, you can now set in `~/.config/drom/config`:
```
dev-tools = [ "merlin", "ocp-indent" ]
```
for example, and they will be installed by `drom dev-deps`.
Still need some documentation in quickstart.
