### ISSUE TITLE
add hooks on various sub-commands

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/drom#76]
Version 0.2.1 introduces a hook `scripts/before-sphinx.sh` that is ran before calling `sphinx-builder`. It can be used for example to generate documentation files. Such hooks could be interesting to add for other commands:
* `drom build` could run `scripts/before-build.sh` after installing the _opam switch (could be used to run `./configure`) and `scripts/after-build.sh` after the build
* `drom test` could run `scripts/before-test.sh` and `scripts/after-test.sh`
* `drom install` could run `scripts/before-install.sh` and `scripts/after-install.sh`
* `drom uninstall` could run `scripts/before-uninstall.sh` and `scripts/after-uninstall.sh`
* `drom publish` could run `scripts/after-publish.sh $OPAM_REPO_DIR`

**Comment by lefessan** [comment]
See PR #98

**Comment by zapashcanon** [comment]
@lefessan this can be closed, right ?
